### ISSUE TITLE
Es más fácil si la redirección de las páginas las haces en build.sh en lugar de en cada script de cada página

### ISSUE THREAD

**Issue by selairi** [PedregalG/EjercicioIntegrador#1]
Hola,
Es más fácil poner en build.sh:
pagina1.sh > web/pagina1.sh
Que hacer las redirecciones en cada script de cada página. Fíjate que es menos código.
Los scripts de las páginas suelen soltar sus contenidos directamente a la terminal.
Un saludo

**Comment by PedregalG** [comment]
Buenos días.

Tienes toda la razón.
Voy a modificar los scripts y los vuelvo a subir.

Gracias por el aporte.
Un saludo.

**Comment by PedregalG** [comment]
Buenos días.

Tienes toda la razón.
Voy a modificar los scripts y los vuelvo a subir.

Gracias por el aporte.
Un saludo.
